version: "3"

services:

  doeat:
  
    # environment:
    #   POSTGRES_USER: admin
    #   POSTGRES_PASSWORD: admin
    #   POSTGRES_DB: do_eat
    #   POSTGRES_HOST: postgres
    #   NODE_ENV: production
    #   PORT: 5432

    build:  # build an image when compose
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    image: "doeat:latest"
    ports:
      - "3000:3000"

  postgres:
    # postgres version 14
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: do_eat
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data